version: "3.8"

name: ${PROJECT}

services:
  base:
    image: ${PROJECT}-base
    build:
      dockerfile: ./__project/docker/Dockerfile.base
      args:
        - PROJECT=${PROJECT}
        - ENVIRONMENT=${ENVIRONMENT}
        - UID=${UID}
        - GID=${GID}
        - USER=${USER}
        - DDIR=${DDIR}
        - VENV=${VENV}
    volumes:
      - ./:/application        
  work:
    container_name: work
    build:
      args:
        - PROJECT=${PROJECT}
      dockerfile: ./__project/docker/Dockerfile.work
    env_file:
      - .env
    depends_on:
      - base      
    volumes:
      - ~/:${HOME}
      - ./:/application
    ports:
      - "8080:8080"
    tty: true

    