FROM python:3.11

ARG PROJECT
ARG ENVIRONMENT
ARG USER
ARG UID
ARG GID
ARG VENV
ARG DDIR
ARG RQR=$DDIR/dependencies/requirements
ARG PIP=$VENV/bin/pip

RUN echo ${USER}:x:${UID}:${GID}:${USER}:/home/${USER}:/bin/bash >> /etc/passwd

WORKDIR /application
COPY $RQR $RQR
RUN python -m venv $VENV

RUN $PIP install -r $RQR/_internal.txt
RUN $PIP install -r $RQR/${ENVIRONMENT}.txt



